---
# Install Partition Manager to the given AWS endpoint.
#
# Copyright (c) 2023 David E Minor
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

- name: Validate global settings
  gather_facts: false
  become: false
  hosts: 127.0.0.1
  connection: local
  tasks:
    - assert:
        that:
          - endpoint is defined
      when: primary is not defined
    
    - assert:
        that:
          - instance is defined
      when: primary is defined

    - name: Set Default
      set_fact:
        primary: "{{ primary | default('127.0.0.1')}}"

- name: Install Partition Manager on AWS
  gather_facts: false
  become: false
  hosts: 127.0.0.1
  connection: local 
  tasks:
    - include_role:
        name: gds_pm
      when: hostvars['endpoint'] is defined

- name: Install Partition Manager on prem
  gather_facts: false
  become: true
  hosts: 
    - "{{primary|default('127.0.0.1') }}"
  tasks:
    - include_role:
        name: gds_pm
      when: hostvars['primary'] != '127.0.0.1'

